function showstats_( hfig )
% show status window
%
% SHOWSTATS_( hfig )
%
% INPUT
% hfig : figure handle (TODO)

		% safeguard
	if nargin < 1
		error( 'invalid argument: hfig' );
	end

		% show status window
	gdata = getappdata( hfig, 'gdata' );

	statstr = {...
		'VIEW', ...
		sprintf( 'vres: %s', util.any2str( gdata.vres ) ), ...
		sprintf( 'vtl: %s', util.any2str( gdata.vtl ) ), ...
		sprintf( 'vcenter: %s', util.any2str( gdata.vcenter ) ), ...
		sprintf( 'vwidth: %s', util.any2str( gdata.vwidth ) ), ...
		'', ...
		'TOGGLES', ...
		sprintf( 'fdyn: %s', util.any2str( gdata.fdyn ) ), ...
		sprintf( 'fmovs: %s', util.any2str( gdata.fmovs ) ), ...
		sprintf( 'fsigs: %s', util.any2str( gdata.fsigs ) ), ...
		sprintf( 'fdata: %s', util.any2str( gdata.fdata ) ), ...
		sprintf( 'fdebug: %s', util.any2str( gdata.fdebug ) ), ...
		'', ...
		'FILTER', ...
		sprintf( 'filtin: %s', util.any2str( gdata.filtin ) ), ...
		sprintf( 'filtex: %s', util.any2str( gdata.filtex ) ), ...
		sprintf( 'filtsel: %s', util.any2str( gdata.filtsel ) ) };
		
	msgbox( statstr, 'nvis:status', 'none', 'modal' );

end % function

